Terrain Generation Base
apetavern/sbox-terryform pull request #70
Opened 2021-11-29 19:35 UTC by trundler-dev

We should do an analysis of these changes and figure out what we need to make this functional for a basic demo.

2021-11-29 19:44 UTC, ShadowBrian commented
pog

2021-11-29 21:15 UTC, xezno requested changes

2021-11-29 21:15 UTC, xezno commented on code/Pawn/Worm.cs
> +					int bonker = Input.Pressed( InputButton.Attack1 ) ? 1 : (Input.Pressed( InputButton.Attack2 ) ? 0 : -1);
What is bonker

2021-11-29 21:15 UTC, xezno commented on code/Terrain/EdgeVertex.cs
> +﻿#region Assembly Sandbox.Game, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
You left in the decompile headers

2021-11-30 02:36 UTC, trundler-dev commented
Changes look good. Tomorrow I'll probably go through and start creating some issues for things we need to do (such as updating player controller, spawning, update test map).

2021-11-30 12:27 UTC, xezno approved these changes
LGTM

2021-11-30 13:07 UTC, merged